### ISSUE TITLE
laser resistant plates unable to be copypasted

### ISSUE THREAD

**Issue by bluhbipo** [RecursivePineapple/MatterManipulator#11]
![2024-12-20_22 11 05](https://github.com/user-attachments/assets/e04664a9-ed3f-4516-b0ba-34ff5882bab5)
you shall note in the above figure that this shit is not finished placing as the chat would lead you to believe

extraly verified by moving the paste region as such:
![2024-12-20_22 12 43](https://github.com/user-attachments/assets/7887ad45-c3ba-463b-81c6-b0f0ae92dc0e)

valve, please fix

**Comment by RecursivePineapple** [comment]
I thought sLaserRender was a fake renderer block, not a real block :pensib:
