### ISSUE TITLE
When removing a block, ore items appears after disconnecting from the quantum uplink

### ISSUE THREAD

**Issue by ABKQPO** [RecursivePineapple/MatterManipulator#6]
![image](https://github.com/user-attachments/assets/991c8612-73f9-4f6c-a021-d5cb703eef10)

**Comment by RecursivePineapple** [comment]
Ores should be voided completely, so that you can still clear out areas underground. If you get the drops from an ore block please let me know.

**Comment by ABKQPO** [comment]
yeah, I have found the problem now
in gtnh 2.7.1,mm0.0.10
when insufficient plasma
![](https://gcdnb.pbrd.co/images/TENnSf3obpfZ.png)

**Comment by ABKQPO** [comment]
yeah I have found the problem now
in gtnh 2.7.1, mm 0.0.10
when insufficient plasma
![](https://gcdnb.pbrd.co/images/TENnSf3obpfZ.png)

**Comment by RecursivePineapple** [comment]
I can't reproduce this. I tried to mine a dozen natural normal & small neutronium ores (MKIII connected to an offline uplink) and it's not giving me any ore.
If you can find more specific steps I'll test this again.

**Comment by ABKQPO** [comment]
When connected to Uplink and only a little bit of plasma is supplied, such a problem can arise at the moment when the plasma is consumed
