### ISSUE TITLE
Add 3d gizmo to edit transform

### ISSUE THREAD

**Issue by SKProCH** [RecursivePineapple/MatterManipulator#8]
I think its worth to add a 3d gizmo to "edit transform" mode for easer understanding axies:

![image](https://github.com/user-attachments/assets/e64b27e1-3fff-4a16-821b-461de2cd9809)

Seems like angelica already has one:

![image](https://github.com/user-attachments/assets/a748d128-ac35-4997-9b4b-104017848f7a)

But i think it would be nice if axies will be labeled (x, y, z), and gizmo shown by default in this mode.

**Comment by RecursivePineapple** [comment]
How's this? I'm not sure if I like it completely but it does the job.

![2024-12-18_23 16 51](https://github.com/user-attachments/assets/75f3935c-1925-4a10-9a16-c3c6d75888dc)

**Comment by SKProCH** [comment]
Yeah, this is fine!
